# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0005_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='defaultServings',
            field=models.IntegerField(null=True),
        ),
    ]
