# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0007_auto_20160407_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='firstDayOfWeek',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6),
        ),
    ]
