# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0009_auto_20160408_0534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='UserSettings',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='user',
            new_name='author',
        ),
    ]
