# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0012_auto_20160411_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='name',
        ),
    ]
